### ISSUE TITLE
Auto Switching causes Switcher to hide instantly if only one window is open

### ISSUE THREAD

**Issue by krmax44** [daniellandau/switcher#77] opened 2019-03-08 10:24 UTC
If I only have one window open, with Auto Switching enabled that means there's only one result which will instantly be selected, causing the Switcher window to hide instantly again with practically no time to start typing (to open a new app).
I know there's `Super + X` but it'd be nice if this could be changed.

Thanks for the handy extension! :+1:

**Comment by esauvisky** [comment] 2019-03-09 02:32
I can confirm. It sort of makes sense, I mean, I can definitely understand why this happens. 

On the other hand, if you have _no_ window open at all, the switcher _does_ stay open on the screen.

IMO, it looks like it's easy to fix by bypassing Auto Switching flag given that:
- the text input is empty, and
- there are less or equal than one window open.

_Yet again I have never looked into the code, so take it with a grain of salt_ :joy:

**Comment by krmax44** [comment] 2019-03-09 11:34
> I can confirm. It sort of makes sense, I mean, I can definitely understand why this happens.
> 
> On the other hand, if you have _no_ window open at all, the switcher _does_ stay open on the screen.
> 
> At first glance, an easy fix would be bypassing the Auto Switching if and only if:
> 
>     * the text input is empty, and
> 
>     * there are less or equal than one window open.
> 
> 
> _Yet again I have never looked into the code, so take it with a grain of salt_ joy
> 
> ** --- Edit ---**
> It seems I had an old version. If no windows are open at all, it opens the Launcher even if you press the Switch combination, that's beautiful, great job. clap

Yup, was thinking of something similar. We're so close to perfection anyhow, might as well add that :smile:

**Comment by daniellandau** [comment] 2019-03-09 14:12
Yeah, switching to the only window open automatically doesn't seem that sensible. I'll try to cook something up soon.

**Comment by daniellandau** [comment] 2019-03-09 18:09
This is fixed by https://github.com/daniellandau/switcher/commit/9bc402e40e8cae67effcbbf746b502160f4f37e2 and I just submitted a new version to extensions.gnome.org. It should show up there eventually after review.

**Closed by daniellandau** 2019-03-09 18:09 UTC

**Comment by krmax44** [comment] 2019-03-10 17:02
Awesome, thank you! :tada:
