### ISSUE TITLE
Badly placed on two-monitor setup

### ISSUE THREAD

**Issue by andrewazores** [daniellandau/switcher#131] opened 2021-02-09 15:13 UTC
![Screenshot from 2021-02-09 10-05-47](https://user-images.githubusercontent.com/3787464/107383169-a352c680-6ae8-11eb-89a4-a83111fdbbeb.png)

In this screenshot, I have a Firefox window open taking up all of my primary/left monitor in a landscape orientation. The image of a road going through hills is my wallpaper, which is shown on a secondary monitor to the right in a portrait orientation. There is some kind of graphical artifact also displayed in some buffer space around the Firefox window on the left monitor - I'm not sure the exact cause of this.

The Switcher overlay appears positioned correctly left-right centered on the primary display, but quite high up. I am only able to see the bottom 4 entries of the 10 when summoned in app launcher mode, for example. The top of this monitor is delimited by the GNOME top bar which is visible just above the Firefox window.

I have verified that this still occurs with the exact same behaviour when all other GNOME Shell Extensions are disabled.

I am running Fedora 33 / GNOME 3.38.2 and in Xorg.

**Comment by andrewazores** [comment] 2021-02-09 16:25
#86 is somewhat related.

**Comment by mr-smith2** [comment] 2021-02-21 21:27
When running 3 monitors the UI crosses over monitors. My center (primary) monitor is 4k and both side monitors are 1920x1080.  Configured with "Show switcher on active display" on.

1. When focus is in window on left monitor, switcher shows correctly on left display.
2. When focus is in window on middle monitor, switcher shows on right side of left monitor.  And overflows into the middle monitor.  It looks like the coordinates are correct but is displayed relative to the left monitor instead of the middle monitor.
3. When focus is in window on right monitor, switcher appears on the left display.  I am guessing it is seeing the coordinates are invalid and defaulting to displaying on the first monitor.

If I position the left and right monitors to be aligned at the bottom (i.e. the display settings have the two smaller monitors lined up at the bottom of the 4k monitor) then the switcher UI is invisible.  It is positioned above the location of the left monitor.

See attached screenshots to clarify what I mean by top and bottom monitor positioning.
![Monitors positioned at top](https://user-images.githubusercontent.com/38927648/108639265-44327180-7459-11eb-8860-0dc7c9fd3987.png)
![Monitors positioned at bottom](https://user-images.githubusercontent.com/38927648/108639271-472d6200-7459-11eb-9042-7c1b3b2b5567.png)

**Comment by daniellandau** [comment] 2021-02-26 20:10
The version in master (and soon to be on extensions.gnome.org, after review there) has better positioning code, but I'm not sure if it fixes either of the issues raised here. It very well might. Please report back if/when you have a chance to test the new code. I can also get access to a 4K monitor at some point, but I don't use one regularly.

**Comment by mr-smith2** [comment] 2021-02-27 01:37
Thanks daniellandau.  I can't say I am savvy enough to pull the master and run it.  But once it is updated in extensions.gnome.org I will test it out and let you know.

**Comment by mr-smith2** [comment] 2021-02-27 01:44
Hi @daniellandau.  I can confirm the problem is fixed in my scenario.  And BTW, thank you for including install instructions in your README.md.  I had installed your extension using extensions.gnome.org and wasn't aware of how to install gnome extensions.

**Comment by daniellandau** [comment] 2021-03-02 07:38
I tested now with a vertical monitor too and it was working properly.

**Closed by daniellandau** 2021-03-02 07:38 UTC
